variables:
  configureMultiRegion: $(check)
  
stages:
- stage: 'release'
  displayName: 'Release'

  jobs:
  - job: 'Configure'
    pool:
     name: Hosted VS2017
    steps:
    - checkout: self
      clean: true
      persistCredentials: true
      
    - task: AzureCLI@1
      displayName: 'Azure CLI FrontDoor-AuditDeployementVersion.bat'
      inputs:
        azureSubscription: PstuffsServicesConnection
        scriptPath: 'FrontDoor-AuditDeployementVersion.bat'
        arguments: '$(Build.SourceBranch) $(Build.SourcesDirectory)'

    - powershell: |
        $timestamp=$true
        Write-Host $timestamp
        Write-Host "##vso[task.setvariable variable=timestamp;isOutput=true]$timestamp"
      displayName: 'mytask'
      name: setvarStep
        
  - job: 'Process'
    dependsOn: Configure
    condition: eq(dependencies.Configure.outputs['setvarStep.timestamp'], 'false')
    variables:
      boolValue: $[dependencies.Configure.outputs['setvarStep.timestamp']]
    pool:
      name: Hosted VS2017
    steps:
    - powershell: |
        Write-Host "$(boolValue)"
      condition: eq(variables.boolValue, false)
 
