variables:
  configureMultiRegion: $(check)
  
stages:
- stage: 'release'
  displayName: 'Release'

  jobs:
  - job: 'Configure'
    pool:
     name: Hosted VS2017
    steps:
    - powershell: |
        $timestamp=$true
        Write-Host $timestamp
        Write-Host "##vso[task.setvariable variable=timestamp;isOutput=true]$timestamp"
      displayName: 'mytask'
      name: setvarStep
        
  - job: 'Process'
    dependsOn: Configure
    variables:
      boolValue: $[dependencies.Configure.outputs['setvarStep.timestamp']]
    pool:
      name: Hosted VS2017
    steps:
    - powershell: |
        Write-Host "$(boolValue)"
      condition: variables.boolValue
