variables:
  configureMultiRegion: $(check)

stages:
- stage: 'Prepare'
  displayName: 'Prepare'
  
  jobs:
  - job: 'Setup'
    condition: eq(variables.configureMultiRegiona, true)
    pool:
      name: Hosted VS2017
    variables:
      configureMultiRegiona: $(check)
    steps:
    - task: DotNetCoreInstaller@0
      displayName: 'Install'
      inputs:
        packageType: 'sdk'
        version: '2.2.105'
  
