variables:
  buildConfiguration: 'Release'
  buildPlatform: 'any cpu'
  version: '0.2.0'
  azureSubscription: 'Azure.Nupaya'
  azureAppType: 'Web App on Windows'
  webAppName: 'api'
  configureMultiRegion: $(Parameters.configureMultiRegion)

stages:

- stage: 'Prepare'
  displayName: 'Prepare'
  
  jobs:

  - job: 'Setup'
    condition: true
    pool:
      name: Hosted VS2017
    steps:
    - task: DotNetCoreInstaller@0
      
      displayName: 'Install'
      inputs:
        packageType: 'sdk'
        version: '2.2.105'
        
- stage: 'deploy'
  displayName: 'deploy'
  jobs:

  - job: 'deploy'
    condition: false
    pool:
      name: Hosted VS2017
    steps:
    - powershell: |
       $timestamp=Get-Date -format "yyyy-MM-ddThh:mm:ss:fffZ"
       Write-Host "##vso[task.setvariable variable=timestamp;]$timestamp"
      displayName: 'PowerShell Script: Set current timespan'
