variables:
  configureMultiRegion: $(check)
  
stages:
- stage: 'release'
  displayName: 'Release'

  jobs:
  - job: 'Configure'
    pool:
     name: Hosted VS2017
    steps:
    - powershell: |
        Write-Host ##vso[task.setvariable variable=test;]$true
        
  - job: 'Process'
    dependsOn: Configure
    pool:
      name: Hosted VS2017
    steps:
    - powershell: |
        Write-Host $(test)
