variables:
  configureMultiRegion: $(check)
  
stages:
- stage: 'release'
  displayName: 'Release'

  jobs:
  - job: 'Configure'
    pool:
     name: Hosted VS2017
    steps:
    - script: |
        ECHO ##vso[task.setvariable variable=test;]true
        
  - job: 'Process'
    variables:
      Build.SyncSources: false
    pool:
      name: Hosted VS2017
    steps:
    - script: |
        ECHO $(test)
