variables:
  configureMultiRegion: $(check)
stages:
- stage: 'Prepare'
  displayName: 'Prepare'
  jobs:
  - job: 'Setup'
    pool:
      name: Hosted VS2017
    steps:
    - task: DotNetCoreInstaller@0
      condition: eq(variables.configureMultiRegion, true)
      displayName: 'Install'
      inputs:
        packageType: 'sdk'
        version: '2.2.105'
  
